version: '3.8'

services:
  potree:
    build:
      context: .
      dockerfile: Dockerfile
    image: potree:latest
    container_name: potree_vps_ubuntu24
    ports:
      - "3000:80" # host:container (hostPort:containerPort)
    restart: unless-stopped
    # Mount local pointclouds directory (optional) so you can update data without rebuilding
    volumes:
      - ./pointclouds:/usr/share/nginx/html/pointclouds:ro
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://localhost/ || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3

  api:
    image: node:18.18.0-alpine
    container_name: potree_api
    working_dir: /app
    command: sh -c "npm install --production && node server.js"
    volumes:
      - ./:/app
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
    restart: unless-stopped

 